import type { Metadata } from "next";
import { Dongle } from "next/font/google";
import "./globals.css";
import Header from "@/app/componenet/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dongle = Dongle({
  weight: ["700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kor">
      <body className={`${dongle.className} max-w-screen-xl mx-auto h-screen`}>
        <Header />
        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
